# Generated by Django 2.2.10 on 2020-10-15 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(db_column='question_id', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Ответ текстом'), ('radio', 'Ответ с выбором одного варианта'), ('checkbox', 'Ответ с выбором нескольких вариантов')], db_column='question_type', default='text', help_text='Например: radio', max_length=8, verbose_name='Тип ответа на вопрос')),
                ('text', models.TextField(db_column='question_text', default=None, help_text='Например: Есть ли у Вас замечания?', max_length=127, verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
                'ordering': ['survey', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(db_column='survey_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='survey_name', default='Опрос', help_text='Например: Опрос о качестве услуг', max_length=127, verbose_name='Название опроса')),
                ('start_date', models.DateField(blank=True, db_column='survey_start_date', default=datetime.date(2020, 10, 15), editable=False, verbose_name='Дата начала')),
                ('end_date', models.DateField(db_column='survey_end_date', default=None, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, db_column='survey_description', default=None, help_text='Например: Цель опроса -- получить оценку работы сотрудников Компании и стать лучше.', max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'survey',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(db_column='response_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='response_user_id', default=None, help_text='Например: 1234', max_length=8, verbose_name='Идентификатор анонимного пользователя')),
                ('survey', models.ForeignKey(db_column='survey_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.Survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'response',
                'ordering': ['survey', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(db_column='question_option_id', primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='question_option_text', default=None, help_text='Например: Скорее положительно', max_length=127, verbose_name='Текст варианта ответа')),
                ('question', models.ForeignKey(db_column='question_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='surveys.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'db_table': 'question_option',
                'ordering': ['question', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(db_column='survey_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.Survey', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(db_column='answer_id', primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, db_column='answer_text', default=None, help_text='Например: Замечаний нет', max_length=255, null=True, verbose_name='Текст ответа')),
                ('question', models.ForeignKey(db_column='question_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='surveys.Question', verbose_name='Вопрос')),
                ('question_option', models.ForeignKey(blank=True, db_column='question_option_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='surveys.QuestionOption', verbose_name='Вариант ответа')),
                ('response', models.ForeignKey(db_column='response_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Response', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answer',
                'ordering': ['response', 'question'],
            },
        ),
    ]
